export function createInitialState(width, height) {
  return {
  player: {
    x: width / 2,
    y: height / 2,
    radius: 14,
    speed: 240,
    health: 100,
    maxHealth: 100,
    level: 1,
    xp: 0,
    xpToNext: 20,
    bulletSpeedMult: 1,
    bulletDamage: 1,
    attackCooldownMult: 1,
    xpGainMult: 1,
    orbPullMult: 1,
    detectionRange: 500,
    projectileCount: 1,
    pierce: 0,
    forkCount: 0,
    specialAttackCount: 0,
    heatSeeking: false,
    regenRate: 0,
    regenTimer: 0,
    aoeEnabled: false,
    aoeRadius: 120,
    aoeDamage: 1,
    aoeTimer: 0,
    aoeTickInterval: 0.5,
  },
  displayHealth: 100,
  healthText: 100,
  healthUpdateTimer: 0,
  bullets: [],
  enemies: [],
  orbs: [],
  items: [],
  inventory: [],
  inventoryCapacity: 60,
  inventoryOpen: false,
  inventoryDragIndex: -1,
  equipmentDragSlot: null,
  socketDragSource: null,
  moduleDragIndex: -1,
  inventoryHoverIndex: -1,
  equipmentHoverSlot: null,
  moduleHoverIndex: -1,
  hoveredSocketGem: null,
  equipment: {
    head: null, amulet: null, chest: null, gloves: null, belt: null,
    boots: null, mainHand: null, offHand: null, ring1: null, ring2: null
  },
  moduleSlots: [null, null, null],
  inventoryMouseX: 0,
  inventoryMouseY: 0,
  popupTexts: [],
  cookEffects: [],
  explosions: [],
  levelUpEffects: [],
  particles: [],
  groundFires: [],
  stars: [],
  score: 0,
  wave: 1,
  time: 0,
  lastShot: 0,
  lastFireball: 0,
  spawnTimer: 0,
  lastBossLevel: 0,
  bossActive: false,
  nullweaveDropped: false,
  gameOver: false,
  paused: false,
  showEnemyHealth: true,
  enemyHealthToggleRect: null,
  triplePickupPull: true,
  pickupPullToggleRect: null,
  tripleShootDistance: true,
  shootDistanceToggleRect: null,
  renderScale: 1,
  renderScaleSliderRect: null,
  draggingRenderScale: false,
  lastRenderScaleSoundStep: 100,
  levelUpActive: false,
  skillPoints: 0,
  cardRects: [],
  skillHoverIndex: -1,
  skillMouseX: 0,
  skillMouseY: 0
  };
}
